"""add cancelled job status

Revision ID: 9f257a8c4b3b
Revises: 76c5c1ea6bf4
Create Date: 2026-09-13 12:44:39.210061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f257a8c4b3b'
down_revision: Union[str, Sequence[str], None] = '76c5c1ea6bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
