"""add cancelled job status

Revision ID: a3f6407774af
Revises: 9f257a8c4b3b
Create Date: 2026-09-13 12:45:28.300323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f6407774af'
down_revision: Union[str, Sequence[str], None] = '9f257a8c4b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'CANCELLED'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
